"use strict";

var extend = require('backbone-extend-standalone');
var Template = function(){console.log("success");};
Template.content = [
  //'<script src="./js/backups/jquery-1.11.1.min.js"></script>',
  //'<script>function() {$( "#tabs" ).tabs();}</script>',
  '<style>.question {background: rgba(211, 211, 211, 0.3);font-weight: 800;font-size:13px;line-height:145%;font-color:#000000;}',
  '#tabs-1 {color:#000000;font-size:12px;font-weight:670;line-height:155%;}',
  '.annotator-widget {font-size:115%;} input[type="radio"] { -webkit-appearance: radio; }</style>',

  '<script type="text/javascript">',
  /*'$(document).ready(function () {',
    '$("#splitter").jqxSplitter({ width: 1270, height: "100%",  panels: [{ size: "65%", min: 100 }, { size: "35%", min: 0}] });',
    '$(".btn-success").val("show");',
  '});',*/
    'function selectDrug() {',
    'var drug1 = $("#Drug1").val();',
    'var drug2 = $("#Drug2").val();',
    'var quotestring = $("#quote").html();',
    'quotestring = quotestring.replace(drug2, "<span class=\'selecteddrug\'>"+drug2+"</span>");',
    'quotestring = quotestring.replace(drug1, "<span class=\'selecteddrug\'>"+drug1+"</span>");',
    '$("#quote").html(quotestring);',
    '}',
    'function deselectDrug() {',
    'var drug1 = $("#Drug1").val();',
    'var drug2 = $("#Drug2").val();',
    'var quotestring = $("#quote").html();',
    'quotestring = quotestring.replace(\'<span class="selecteddrug">\'+drug2+\'</span>\', drug2);',
    'quotestring = quotestring.replace(\'<span class="selecteddrug">\'+drug1+\'</span>\', drug1);',
    '$("#quote").html(quotestring);',
    '}',
    'function changeFunc() {',
    'if($("#assertion_type option:selected").text()=="DDI clinical trial"){ $("#altersection").show();$(".moreinfo").show();}',
    'else{ $("#altersection").hide();$(".moreinfo").hide();}',
    //'$("#splitter").jqxSplitter({ width: "100%", height: 650, orientation: "horizontal", panels: [{ size: "50%", min: 100 }, { size: "50%", min: 50}] });',
    '}',

    'function changeRole1(role) {',
    '$(".Role2").each(function(){ if(this.value != role) this.checked = true; else this.checked = false;});}',

    'function changeRole2(role) {',
    '$(".Role1").each(function(){ if(this.value != role) this.checked = true; else this.checked = false;});}',

  '</script>',
  '<div class="annotator-outer  annotator-editor annotator-invert-y annotator-invert-x">',
  '  <form class="annotator-widget">',
  '    <ul class="annotator-listing"></ul>',
  '<div class="annotationbody" style="margin-left:10px;margin-right:10px;height:450px;margin-top:0px;overflow-y:scroll;">',
    '<div id="tabs">',
    //'<ul>',
    //'<li><a href="#tabs-1">PK DDI</a></li>',
  //'</ul>',
  '<div id="tabs-1" style="margin-bottom:30px;">',
  '<div  style="margin-bottom:0px;margin-left=5px">',
  '<div class="question">Drug 1 in DDI:</div>',
  '<div>Drug mentions:',
  '<select id="Drug1" onmouseup="deselectDrug()" onchange="selectDrug()">',
  //'<option value="simvastatin">simvastatin</option>',
  //'<option value="ketoconazole">ketoconazole</option>',
  '</select>',
  '</div>',

  '<div class="question">Type</div>',
  '<div>',
  '<input type="radio" name="Type1" id="Type1" class="Type1" value="active ingredient">active ingredient',
  '<input type="radio" name="Type1" class="Type1" value="metabolite">metabolite',
  '<input type="radio" name="Type1" class="Type1" value="drug product">drug product',
  '<input type="radio" name="Type1" class="Type1" value="drug group">drug group',
  '</div>',

  '<div class="question">Role</div>',
  '<div>',
  '<input type="radio" name="Role1" id="Role1" class="Role1" value="Precipitant" onclick="changeRole1(this.value);"> Precipitant',
  '<input type="radio" name="Role1" id="Role1" class="Role1" value="Object" onclick="changeRole1(this.value);"> Object',
  '</div>',

  '<div class="question">Drug 2 in DDI:</div>',
  '<div>Drug mentions:',
  '<select id="Drug2" onmouseup="deselectDrug()" onchange="selectDrug()">',
  //'<option value="simvastatin">simvastatin</option>',
  //'<option value="ketoconazole">ketoconazole</option>',
  '</select>',
  '</div>',

  '<div class="question">Type</div>',
  '<div>',
  '<input type="radio" name="Type2" id="Type2" class="Type2" value="active_ingredient">active ingredient',
  '<input type="radio" name="Type2" id="Type2" class="Type2" value="metabolite">metabolite',
  '<input type="radio" name="Type2" id="Type2" class="Type2" value="drug_product">drug product',
  '<input type="radio" name="Type2" id="Type2" class="Type2" value="drug_group">drug group',
  '</div>',

  '<div class="question">Role</div>',
  '<div>',
  '<input type="radio" name="Role2" id="Role2" class="Role2" value="Precipitant" onclick="changeRole2(this.value);">Precipitant',
  '<input type="radio" name="Role2" id="Role2" class="Role2" value="Object" onclick="changeRole2(this.value);">Object',
  '</div>',

  '</div>',


  '<div style="margin-left: 0px;">',

  '<div class="question">DIKB Assertion type:</div>',
  '<div>',
  '<select id="assertion_type" onchange="changeFunc();">',
  '<option id="DDI" value="Drug Drug Interaction">Drug Drug Interaction</option>',
  '<option id="clinical" value="DDI clinical trial">DDI clinical trial</option>',
  '</select>',
  '</div>',

  '<div class="question">Modality</div>',
  '<div>',
  '<input type="radio" name="Modality" id="Modality" class="Modality" value="Positive">Positive',
  '<input type="radio" name="Modality" id="Modality" class="Modality" value="Negative">Negative',
  '</div>',

  '<div class="question">Evidence modality</div>',
  '<div>',
  '<input type="radio" name="Evidence_modality" id="Evidence_modality" class="Evidence_modality" value="for">Evidence for',
  '<input type="radio" name="Evidence_modality" id="Evidence_modality" class="Evidence_modality" value="against">Evidence against',
  '</div>',

  '<div class="question">Comment</div>',
  '<div>',
  '<textarea id="Comment" class="Comment"></textarea>',
  '</div>',

  '</div>',

  '<div style="margin-left: 0px;">',
  '<div id = "altersection" style="display: none;">',

  '<div class="question">The number of participants:</div>',
  '<div>',
  '<input type="text" id="Number_participants">',
  '</div>',

  '<div class="question">Precipitant drug dosage:</div>',
  '<div>',
  'Dose in MG: <input style="width:30px;" type="text" id="DoseMG_precipitant">',
  'Formulation: <select id="FormulationP">',
  '<option value="UNK">UNK</option>',
  '<option value="Oral">Oral</option>',
  '<option value="IV">IV</option>',
  '<option value="transdermal">transdermal</option>',
  '</select>',
  'Duration(days): <input style="width:30px;" type="text" id="Duration_precipitant">',
  'Regiments: <select id="RegimentsP">',
  '<option value="UNK">UNK</option>',
  '<option value="SD">SD</option>',
  '<option value="QD">QD</option>',
  '<option value="BID">BID</option>',
  '<option value="TID">TID</option>',
  '<option value="QID">QID</option>',
  '<option value="Q12">Q12</option>',
  '<option value="Q8">Q8</option>',
  '<option value="Q6">Q6</option>',
  '<option value="Daily">Daily</option>',
  '</select>',
  '</div>',

  '<div class="question">Object drug dosage:</div>',
  '<div>',
  'Dose in MG: <input style="width:30px;" type="text" id="DoseMG_object">',
  'Formulation: <select id="FormulationO">',
  '<option value="UNK">UNK</option>',
  '<option value="Oral">Oral</option>',
  '<option value="IV">IV</option>',
  '<option value="transdermal">transdermal</option>',
  '</select>',
  'Duration(days): <input style="width:30px;" type="text" id="Duration_object">',
  'Regiments: <select id="RegimentsO">',
  '<option value="UNK">UNK</option>',
  '<option value="SD">SD</option>',
  '<option value="QD">QD</option>',
  '<option value="BID">BID</option>',
  '<option value="TID">TID</option>',
  '<option value="QID">QID</option>',
  '<option value="Q12">Q12</option>',
  '<option value="Q8">Q8</option>',
  '<option value="Q6">Q6</option>',
  '<option value="Daily">Daily</option>',
  '</select>',
  '</div>',

  '<div class="question">AUC_i/AUC:</div>',
  '<div>',
  'Auc: <input style="width:30px;" type="text" id="Auc">',
  'Type: <select id="AucType">',
  '<option value="UNK">UNK</option>',
  '<option value="Percent">Percent</option>',
  '<option value="Fold">Fold</option>',
  '</select>',
  'Direction: <select id="AucDirection">',
  '<option value="UNK">UNK</option>',
  '<option value="Increase">Increase</option>',
  '<option value="Decrease">Decrease</option>',
  '</select>',
  '</div>',

  '<div class="question">CL_i/CL:</div>',
  '<div>',
  'Cl: <input style="width:30px;" type="text" id="Cl">',
  'Type: <select id="ClType">',
  '<option value="UNK">UNK</option>',
  '<option value="Percent">Percent</option>',
  '<option value="Fold">Fold</option>',
  '</select>',
  'Direction: <select id="ClDirection">',
  '<option value="UNK">UNK</option>',
  '<option value="Increase">Increase</option>',
  '<option value="Decrease">Decrease</option>',
  '</select>',
  '</div>',

  '<div class="question">Cmax:</div>',
  '<div>',
  'cmax: <input style="width:30px;" type="text" id="cmax">',
  'Type: <select id="cmaxType">',
  '<option value="UNK">UNK</option>',
  '<option value="Percent">Percent</option>',
  '<option value="Fold">Fold</option>',
  '</select>',
  'Direction: <select id="cmaxDirection">',
  '<option value="UNK">UNK</option>',
  '<option value="Increase">Increase</option>',
  '<option value="Decrease">Decrease</option>',
  '</select>',
  '</div>',

  '<div class="question">Cmin:</div>',
  '<div>',
  'cmin: <input style="width:30px;" type="text" id="cmin">',
  'Type: <select id="cminType">',
  '<option value="UNK">UNK</option>',
  '<option value="Percent">Percent</option>',
  '<option value="Fold">Fold</option>',
  '</select>',
  'Direction: <select id="cminDirection">',
  '<option value="UNK">UNK</option>',
  '<option value="Increase">Increase</option>',
  '<option value="Decrease">Decrease</option>',
  '</select>',
  '</div>',

  '<div class="question">T1/2:</div>',
  '<div>',
  't12: <input style="width:30px;" type="text" id="t12">',
  'Type: <select id="t12Type">',
  '<option value="UNK">UNK</option>',
  '<option value="Percent">Percent</option>',
  '<option value="Fold">Fold</option>',
  '</select>',
  'Direction: <select id="t12Direction">',
  '<option value="UNK">UNK</option>',
  '<option value="Increase">Increase</option>',
  '<option value="Decrease">Decrease</option>',
  '</select>',
  '</div>',

  '</div>',
  '</div>',

  '</div>',
  '</div>',
  '</div>',
  '    <div class="annotator-controls">',
  '     <a href="#cancel" class="annotator-cancel" onclick="showrightbyvalue()" id="annotator-cancel">',
  'Cancel',
  '</a>',
  '      <a href="#save"',
  '         class="annotator-save annotator-focus" onclick="showrightbyvalue()">',
  'Save',
  '</a>',
  '    </div>',
    '<div class="moreinfo" style="display: none;">  <b>Scroll down to show more information</b></div>',
  '  </form>',
  '</div>'
].join('\n');


Template.extend = extend;
exports.Template = Template;
