#!/usr/bin/env node
var child_process = require('child_process');
var fs = require('fs');
var path = require('path');

var browserify = require('browserify');
var coffee = require('coffee-script');
var coffeeify = require('caching-coffeeify');
var convert = require('convert-source-map');
var glob = require('glob');
var q = require('kew');
var sourceMap = require('source-map');
var through = require('through');
var UglifyJS = require('uglify-js');
var UglifyCSS = require('uglifycss');

var annotator = require('../');

var SourceMapConsumer = sourceMap.SourceMapConsumer;
var SourceMapGenerator = sourceMap.SourceMapGenerator;
var SourceNode = sourceMap.SourceNode;


// Uglify emits ugly warnings for source maps it can't resolve.
// It cannot map our license preamble or the browserify wrappers.
// It feels ugly, but let's just disable these.
UglifyJS.AST_Node.warn_function = null;


// Uglify a source with the supplied source map generator.
// Returns {code::String, map::SourceMapGenerator}
function uglify(src, srcMap) {
  var comment = '//# sourceMappingURL=';
  var inSrcMap = convert.fromJSON(srcMap.toString());
  var filename = inSrcMap.getProperty('file').replace('.js', '.min.js');

  // Parse the result with UglifyJS
  var ast = UglifyJS.parse(src, {filename: inSrcMap.getProperty('file')});

  // Set up the UglifyJS compression pipeline
  srcMap = UglifyJS.SourceMap({
    file: path.basename(filename),
    orig: srcMap.toString(),
    root: inSrcMap.getProperty('sourceRoot')
  });
  src = UglifyJS.OutputStream({
    comments: /Copyright/g,
    source_map: srcMap
  });

  // Perform the minification
  ast.figure_out_scope();
  ast = ast.transform(UglifyJS.Compressor());
  ast.figure_out_scope();
  ast.compute_char_frequency();
  ast.mangle_names();
  ast.print(src);

  // Read the source and source map from the uglify pipeline
  src = src.get() + '\n' + comment + filename.replace('pkg/', '') + '.map';
  srcMap = convert.fromJSON(srcMap.toString());

  // Add all the sources into the source map
  srcMap.setProperty('sourcesContent', inSrcMap.getProperty('sourcesContent'));

  srcMap = SourceMapGenerator.fromSourceMap(
    new SourceMapConsumer(srcMap.toObject())
  );

  return {code: src, map: srcMap};
}


// The core Annotator library
exports.annotator = function (browserify) {
  return browserify({extensions: ['.coffee']})
    .require('./src/annotator', {entry: true})
    .transform(coffeeify)
  ;
};


// The plugin bundles
exports.plugin = function (browserify, p) {
  var name = path.basename(p).replace('.coffee', '');
  var expose = ['annotator', 'plugin', name].join('-').replace('.js', '');

  var b = browserify({extensions: ['.coffee']})
    .require('./src/namespace', {expose: 'annotator'})
    .require(p, {expose: expose})
    .transform(coffeeify);

  return annotator.loader(b);
};


// Test files
exports.test = function (browserify, t) {
  return browserify({entries: [t], extensions: ['.coffee']})
    .external('annotator')
    .external('helpers')
    .transform(coffeeify)
  ;
};


// Package the bundles when called as the main script
if (require.main === module) {
  var depsOnly = false;
  var libs = {};
  var preamble = null;
  var targets = Array.prototype.slice.call(process.argv, 2);

  child_process.exec('./tools/preamble', function (err, preambleSrc) {
    if (err) throw (err);
    preamble = coffee.compile(preambleSrc, {bare: true}).trim() + '\n';

    while(targets.length) {
      var target = targets.shift();

      switch (target) {
      case '-c':
        css();
        break;
      case '-d':
        depsOnly = true;
        break;
      case 'annotator':
        core();
        break;
      case '-p':
        plugin(targets.shift());
        break;
      case 'annotator-full':
        full();
        break;
      case undefined:
        return;
      default:
        console.error('Unrecognized target:', target);
        process.exit(64);
        break;
      }
    }
  });

  function write(filename, node) {
    if (depsOnly) return process.stdout.write(node);
    node.prepend(preamble);

    // Output the source with the preamble appended
    var output = node.toStringWithSourceMap({file: filename});
    console.log('Writing', filename);
    fs.writeFileSync(filename, [
      output.code,
      convert.fromJSON(output.map.toString()).toComment()
    ].join('\n'));

    // Compress the source
    var compressed = uglify(output.code, output.map);

    // Write the minified source
    filename = filename.replace('.js', '.min.js');
    console.log('Writing', filename);
    fs.writeFileSync(filename, compressed.code);

    // Write the minified source map
    filename += '.map';
    console.log('Writing', filename);
    fs.writeFileSync(filename, compressed.map.toString());

    return node;
  }

  function css() {
    var src = '';
    var dataURI = child_process.spawn('./tools/data_uri_ify');

    fs.createReadStream('./css/annotator.css').pipe(dataURI.stdin);
    dataURI.stdout.pipe(through(write, end));

    function write (data) { src += data; }
    function end() {
      this.queue(null);

      console.log('Writing', 'pkg/annotator.css');
      fs.writeFileSync('pkg/annotator.css', preamble + src);

      src = UglifyCSS.processString(src);
      console.log('Writing', 'pkg/annotator.min.css');
      fs.writeFileSync('pkg/annotator.min.css', preamble + src);
    }
  }

  function core () {
    pack(exports.annotator(browserify), 'pkg/annotator.js', {
      debug: true,
      standalone: 'Annotator'
    });
  }

  function plugin(name) {
    var source = './src/plugin/' + name + '.coffee';
    var target = 'pkg/annotator.' + path.basename(name) + '.js';
    pack(exports.plugin(browserify, source), target, {
      debug: true,
      standalone: 'Annotator'
    });
  }

  function full() {
    var b = annotator.loader(browserify({extensions: '.coffee'}));
    b.require('./src/annotator', {expose: 'annotator'});
    b.transform(coffeeify);
    glob.sync('./src/plugin/*.coffee').forEach(function (p) {
      var name = path.basename(p).replace('.coffee', '');
      var expose = ['annotator', 'plugin', name].join('-').replace('.js', '');
      b.require(p, {expose: expose});
    });
    pack(b, 'pkg/annotator-full.js', {
      debug: true,
      standalone: 'Annotator'
    });
  }

  function pack(b, filename, options) {
    var deps = '';
    var ignore = /(_empty)|(fake_[a-z0-9]+).js$/;
    var promise = q.defer();

    if (depsOnly) {
      options.noParse = b._noParse;
      options.resolve = b._resolve.bind(b);
      options.transform = b._transforms;

      b.deps(options).pipe(through(logdeps));

      function logdeps(dep) {
        if (dep.id.match(ignore)) return;
        console.log(dep.id);
      }
    } else {
      b.bundle(options, function (err, result) {
        if (err) throw err;
        var src = convert.removeComments(result).slice(0, -3);
        var srcMap = convert.fromSource(result).toObject();

        // Make the source file paths relative
        srcMap.sources = srcMap.sources.map(function (src) {
          return path.relative('./src', src);
        });
        srcMap.file = path.basename(filename);

        var consumer = new SourceMapConsumer(srcMap);
        var node = SourceNode.fromStringWithSourceMap(src, consumer);
        write(filename, node);
      });

      b.on('dep', function (row) {
        if (row.id.match(ignore)) return;
        var filename = path.relative(process.cwd(), row.id)
          .replace('src', 'pkg/lib')
          .replace('.coffee', '.js')
        ;
        if (filename == 'main.js') return;
        if (!libs[filename]) {
          libs[filename] = true;
          fs.writeFileSync(filename, row.source);
        }
      });
    }
  }
}
