#!/bin/bash

abort () {
  echo "Aborting."
  exit 1
}

install () {
  local name=$1
  local cmd=$2
  shift
  shift

  if which "$cmd" >/dev/null 2>&1; then
    echo "Found ${name}..."
  else
    printf "Shall I install ${name} for you? "
    read REPLY
    if [[ "$REPLY" =~ ^(y|Y) ]]; then
      "$@"
    else
      abort
    fi
  fi
}

cd "$(dirname "$0")"
cd ..

if [ "$(uname)" != "Darwin" ]; then
  echo "This script will only work on a Mac at the moment, sorry!"
  abort
fi

install homebrew brew /usr/bin/ruby -e "$(/usr/bin/curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
install node node brew install node
install phantomjs phantomjs brew install phantomjs

echo "Running 'npm install'..."
npm install

echo
echo "Excellent. You should now be able to run the tests by running"
echo
echo "  make test"
echo
echo "While developing, you might find it useful to auto-compile any "
echo "changes to development sources by running"
echo
echo "  ./tools/watch"
echo
echo "You may also find dev.html useful when developing Annotator."
