#!/usr/bin/env node
var child_process = require('child_process');

var app = require('./serve');

var TEST_RUNNER = 'http://localhost:4001/test/runner.html';
var args = process.argv.slice(2).concat(TEST_RUNNER);

app.listen(4001, function () {
  console.log('Starting test suite...');
  console.log('mocha-phantomjs', args.join(' '));
  child_process.spawn('mocha-phantomjs', args, {stdio: 'inherit'})
    .on('exit', function (code, signal) {
      if (signal) process.kill(process.pid, signal);
      else process.exit(code);
    });
});
